version: '3.4'

services:
  app:
    build:
      context: .
      args:
        DOCKER_USER: ${DOCKER_USER:-1000}
    user: ${DOCKER_USER:-1000}
    image: "${RAMRALPH_IMAGE_NAME:-ramralph}:${RAMRALPH_IMAGE_TAG:-development}"
    volumes:
      - .:/app
